version: "3"

networks:
  backend:
    driver: bridge

volumes:

  ### ignore folder volume #####
  var:
    driver: local
  vendor:
    driver: local
  node_modules:
    driver: local

services:
  ### ECCube4 ##################################
  ec-cube:
    build:
      context: .
      args:
        # ビルド時のECCubeインストールスクリプトをスキップする場合にtrueを指定する。
        # ビルド時点でDBサーバの起動や接続が出来ない、という場合等にエラーとなるため。
        SKIP_INSTALL_SCRIPT_ON_DOCKER_BUILD: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      ### 同期対象からコストの重いフォルダを除外 #####################
      - "var:/var/www/html/var"
      - "vendor:/var/www/html/vendor"
      - "node_modules:/var/www/html/node_modules"

      # デザインテンプレート用のディレクトリをマウント
      - "./nachumaru-data/nadesign/html/assets/img/na:/var/www/html/html/template/default/assets/img/na"
      - "./nachumaru-data/nadesign/app/template/default:/var/www/html/app/template/default"
      # サイトカスタマイズ用のディレクトリをマウント
      #     - "./app/Customize:/var/www/html/app/Customize"
      - "./nachumaru-data/nadesign/app/Customize:/var/www/html/app/Customize"
      
      # 画像アップロードフォルダをマウント
      #- "./html/upload:/var/www/html/html/upload"
      - "./nachumaru-data/html/upload:/var/www/html/html/upload"
      # user_dataフォルダとマウント
      - "./nachumaru-data/html/user_data:/var/www/html/html/user_data"

    networks:
      - backend
    
  ### MySQL ##################################
  mysql:
    # MySqlのarmイメージがないためMariaDBを使用 
    image: mariadb:10.3
    # image: mysql:5.7
    # platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eccubedb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
    volumes:
      - ./nachumaru-data/db:/var/lib/mysql
    ports:
      - 13306:3306
    networks:
      - backend
    user: 1000:1000

