version: "3"

volumes:
  mailcatcher-data:
    driver: local
    
services:
  ### ECCube4 ##################################
  ec-cube:
    volumes:
      # for DEBUG
      - ".:/var/www/html:cached"
      
    environment:
     # EC-CUBE environments
     MAILER_URL: "smtp://mailcatcher:1025"
     
  ### Mailcatcher ##################################
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - backend

